/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `gpp_details` VALUES
(1,1,"1^2^3","ODM House","888-888-8888","test@email","test:website","Student-Led Organization^Faculty-Led Organization^Cal Corps","For Profit / Corporation-Based Development Organization","Kenya","Sub-Saharan Africa","Disaster / Humanitarian Relief^Environment / Sustainability^Microfinance / Small Enterprise","0","3000",1),
(2,3,"4^5^6","Jubilee House","888-888-9090","example@jp.com","http://test.com","No Campus Affiliation^Blum Center^UC Affiliated^Cal Corps","NGO / Non-Profit","United States","North America","Gender Empowerment^Environment / Sustainability^Information Technology","0","2500",2),
(3,5,"7^8^9","Serena Foundation","444-444-4444","test@email.com","test@website.com","Cal Corps^Faculty-Led Organization^UC Affiliated","Social Enterprise / Corporate Social Responsibility","Tanzania, United Republic of","Sub-Saharan Africa","Disaster / Humanitarian Relief^Environment / Sustainability^Microfinance / Small Enterprise","0","5000",1),
(4,7,"10^11^12","United Way","764-890-9090","trincoll@email.com","http://trincol.com","UC Affiliated^Blum Center","Fee-Based Third Party Provider","United States","North America","Healthcare (Basic Heath, HIV/AIDS, Maternal, Child, etc)^Gender Empowerment","0","3000",1),
(5,9,"13^14^15","100 Strong","555-555-5555","100strong.berkeley@gmail.com","www.onehundredstrong.org","Blum Center^UC Affiliated^Student-Led Organization","Social Enterprise / Corporate Social Responsibility","United States","North America","Disaster / Humanitarian Relief^Microfinance / Small Enterprise","0","2500",1),
(6,11,"16^17^18","Because Justice Matters","444-666-5151","teacher@mail.com","http://web.com","No Campus Affiliation","NGO / Non-Profit","United States","North America","Immigration","0","5000",1),
(7,13,"19^20^21","Amani Coalition","","","","Blum Center^UC Affiliated^Cal Corps","Social Enterprise / Corporate Social Responsibility","Kenya","Sub-Saharan Africa","Healthcare (Basic Heath, HIV/AIDS, Maternal, Child, etc)^Human Rights (Housing, Water, Sanitation) / Law^Immigration^Environment / Sustainability^Disaster / Humanitarian Relief","0","4000",1),
(8,15,"22^23^24","NRM Movement","","","","Blum Center^UC Affiliated","Social Enterprise / Corporate Social Responsibility","India","India","Microfinance / Small Enterprise","0","1500",1),
(9,17,"25^26^27","Red Cross","5106438305","etstst@email","http://local.com","No Campus Affiliation","Collection Action Group (union, social movement)","Antarctica","South America","Healthcare (Basic Heath, HIV/AIDS, Maternal, Child, etc)","0","1000",1),
(11,22,"34^35^36","This Is A New Organization","+254-700-8001","example@email.com","http://example.com","Blum Center^Cal Corps^UC Affiliated","For Profit / Corporation-Based Development Organization","Kenya","Sub-Saharan Africa","Collective Mobilization / Advocacy^Gender Empowerment^Fair Trade / Market Access^Environment / Sustainability^Disaster / Humanitarian Relief","0","5000",1);
