app:
    auth:
        token-secret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
        token-expiration-ms: 864000000
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/rateandreview_dev?serverTimezone=UTC
        username: root
        password: 
    graphql:
        graphiql:
            enabled: true
            path: /graphiql
    jpa:
        hibernate:
            ddl-auto: update
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 1035290053103-dk1vnbu3u6gltisofephjlmemmjmt8ps.apps.googleusercontent.com
                        client-secret: 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
                        scope:
                        - email
                        - profile